"""Removed Foreign key from brand_id

Revision ID: 7c1a09141f4b
Revises: 2476fbb3f95e
Create Date: 2024-10-02 22:18:32.766199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c1a09141f4b'
down_revision: Union[str, None] = '2476fbb3f95e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_brand',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], )
    )
    op.add_column('categories', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('collaborations', sa.Column('brand_id', sa.Integer(), nullable=True))
    op.add_column('products', sa.Column('brand_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'brand_id')
    op.drop_column('collaborations', 'brand_id')
    op.drop_column('categories', 'brand_id')
    op.drop_table('category_brand')
    # ### end Alembic commands ###
